package com.android.application.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.email.table.Mail;
import com.email.table.User;

import com.android.application.greendao.MailDao;
import com.android.application.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mailDaoConfig;
    private final DaoConfig userDaoConfig;

    private final MailDao mailDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mailDaoConfig = daoConfigMap.get(MailDao.class).clone();
        mailDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        mailDao = new MailDao(mailDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Mail.class, mailDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        mailDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public MailDao getMailDao() {
        return mailDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
