package com.android.application.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.email.table.Mail;
import com.email.table.User;
import com.email.table.MailBList;
import com.email.table.KeyWord;
import com.email.table.BlackWord;
import com.email.table.WhiteWord;

import com.android.application.greendao.MailDao;
import com.android.application.greendao.UserDao;
import com.android.application.greendao.MailBListDao;
import com.android.application.greendao.KeyWordDao;
import com.android.application.greendao.BlackWordDao;
import com.android.application.greendao.WhiteWordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mailDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig mailBListDaoConfig;
    private final DaoConfig keyWordDaoConfig;
    private final DaoConfig blackWordDaoConfig;
    private final DaoConfig whiteWordDaoConfig;

    private final MailDao mailDao;
    private final UserDao userDao;
    private final MailBListDao mailBListDao;
    private final KeyWordDao keyWordDao;
    private final BlackWordDao blackWordDao;
    private final WhiteWordDao whiteWordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mailDaoConfig = daoConfigMap.get(MailDao.class).clone();
        mailDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        mailBListDaoConfig = daoConfigMap.get(MailBListDao.class).clone();
        mailBListDaoConfig.initIdentityScope(type);

        keyWordDaoConfig = daoConfigMap.get(KeyWordDao.class).clone();
        keyWordDaoConfig.initIdentityScope(type);

        blackWordDaoConfig = daoConfigMap.get(BlackWordDao.class).clone();
        blackWordDaoConfig.initIdentityScope(type);

        whiteWordDaoConfig = daoConfigMap.get(WhiteWordDao.class).clone();
        whiteWordDaoConfig.initIdentityScope(type);

        mailDao = new MailDao(mailDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        mailBListDao = new MailBListDao(mailBListDaoConfig, this);
        keyWordDao = new KeyWordDao(keyWordDaoConfig, this);
        blackWordDao = new BlackWordDao(blackWordDaoConfig, this);
        whiteWordDao = new WhiteWordDao(whiteWordDaoConfig, this);

        registerDao(Mail.class, mailDao);
        registerDao(User.class, userDao);
        registerDao(MailBList.class, mailBListDao);
        registerDao(KeyWord.class, keyWordDao);
        registerDao(BlackWord.class, blackWordDao);
        registerDao(WhiteWord.class, whiteWordDao);
    }
    
    public void clear() {
        mailDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        mailBListDaoConfig.clearIdentityScope();
        keyWordDaoConfig.clearIdentityScope();
        blackWordDaoConfig.clearIdentityScope();
        whiteWordDaoConfig.clearIdentityScope();
    }

    public MailDao getMailDao() {
        return mailDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MailBListDao getMailBListDao() {
        return mailBListDao;
    }

    public KeyWordDao getKeyWordDao() {
        return keyWordDao;
    }

    public BlackWordDao getBlackWordDao() {
        return blackWordDao;
    }

    public WhiteWordDao getWhiteWordDao() {
        return whiteWordDao;
    }

}
