package com.android.application.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.email.table.MailBList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MAIL_BLIST".
*/
public class MailBListDao extends AbstractDao<MailBList, Long> {

    public static final String TABLENAME = "MAIL_BLIST";

    /**
     * Properties of entity MailBList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MailBId = new Property(0, Long.class, "mailBId", true, "_id");
        public final static Property MailAdress = new Property(1, String.class, "mailAdress", false, "MAIL_ADRESS");
    }


    public MailBListDao(DaoConfig config) {
        super(config);
    }
    
    public MailBListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MAIL_BLIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: mailBId
                "\"MAIL_ADRESS\" TEXT);"); // 1: mailAdress
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MAIL_BLIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MailBList entity) {
        stmt.clearBindings();
 
        Long mailBId = entity.getMailBId();
        if (mailBId != null) {
            stmt.bindLong(1, mailBId);
        }
 
        String mailAdress = entity.getMailAdress();
        if (mailAdress != null) {
            stmt.bindString(2, mailAdress);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MailBList entity) {
        stmt.clearBindings();
 
        Long mailBId = entity.getMailBId();
        if (mailBId != null) {
            stmt.bindLong(1, mailBId);
        }
 
        String mailAdress = entity.getMailAdress();
        if (mailAdress != null) {
            stmt.bindString(2, mailAdress);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MailBList readEntity(Cursor cursor, int offset) {
        MailBList entity = new MailBList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // mailBId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // mailAdress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MailBList entity, int offset) {
        entity.setMailBId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMailAdress(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MailBList entity, long rowId) {
        entity.setMailBId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MailBList entity) {
        if(entity != null) {
            return entity.getMailBId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MailBList entity) {
        return entity.getMailBId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
